services:
  - type: web
    name: voltguard-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: MONGO_URI_API
        sync: false
      - key: API_KEY
        sync: false
      - key: DB_NAME
        value: volt_guard
      - key: COLLECTION_NAME
        value: occupancy_telemetry